packages: 
  - 'packages/**'
  - 'scripts'


# 用于替换monorepo仓库中的不同版本的react
# catalogs: 
#   react17:
#     react: ^17.0.2
#     react-dom: ^17.0.2
#   react18:
#     react: ^18.2.0
#     react-dom: ^18.2.0